// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pkg/protocol/proto/peer_protocol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerMessageType enum
type PeerMessageType int32

const (
	PeerMessageType_MSG_HANDSHAKE PeerMessageType = 0
	PeerMessageType_MSG_BITFIELD  PeerMessageType = 1
	PeerMessageType_MSG_HAVE      PeerMessageType = 2
	PeerMessageType_MSG_REQUEST   PeerMessageType = 3
	PeerMessageType_MSG_TRANSFER  PeerMessageType = 4
	PeerMessageType_MSG_REJECT    PeerMessageType = 5
)

// Enum value maps for PeerMessageType.
var (
	PeerMessageType_name = map[int32]string{
		0: "MSG_HANDSHAKE",
		1: "MSG_BITFIELD",
		2: "MSG_HAVE",
		3: "MSG_REQUEST",
		4: "MSG_TRANSFER",
		5: "MSG_REJECT",
	}
	PeerMessageType_value = map[string]int32{
		"MSG_HANDSHAKE": 0,
		"MSG_BITFIELD":  1,
		"MSG_HAVE":      2,
		"MSG_REQUEST":   3,
		"MSG_TRANSFER":  4,
		"MSG_REJECT":    5,
	}
)

func (x PeerMessageType) Enum() *PeerMessageType {
	p := new(PeerMessageType)
	*p = x
	return p
}

func (x PeerMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_proto_peer_protocol_proto_enumTypes[0].Descriptor()
}

func (PeerMessageType) Type() protoreflect.EnumType {
	return &file_pkg_protocol_proto_peer_protocol_proto_enumTypes[0]
}

func (x PeerMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerMessageType.Descriptor instead.
func (PeerMessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{0}
}

// PeerMessage structure
type PeerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      []byte                 `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	Type          PeerMessageType        `protobuf:"varint,2,opt,name=type,proto3,enum=protocol.PeerMessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage) Reset() {
	*x = PeerMessage{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage) ProtoMessage() {}

func (x *PeerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage.ProtoReflect.Descriptor instead.
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *PeerMessage) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *PeerMessage) GetType() PeerMessageType {
	if x != nil {
		return x.Type
	}
	return PeerMessageType_MSG_HANDSHAKE
}

func (x *PeerMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// HandshakePayload structure
type HandshakePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      []byte                 `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakePayload) Reset() {
	*x = HandshakePayload{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakePayload) ProtoMessage() {}

func (x *HandshakePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakePayload.ProtoReflect.Descriptor instead.
func (*HandshakePayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakePayload) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *HandshakePayload) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// BitfieldPayload structure
type BitfieldPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bits          []byte                 `protobuf:"bytes,1,opt,name=bits,proto3" json:"bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitfieldPayload) Reset() {
	*x = BitfieldPayload{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitfieldPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitfieldPayload) ProtoMessage() {}

func (x *BitfieldPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitfieldPayload.ProtoReflect.Descriptor instead.
func (*BitfieldPayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *BitfieldPayload) GetBits() []byte {
	if x != nil {
		return x.Bits
	}
	return nil
}

// HavePayload structure
type HavePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitIndex     uint64                 `protobuf:"varint,1,opt,name=unit_index,json=unitIndex,proto3" json:"unit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HavePayload) Reset() {
	*x = HavePayload{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HavePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavePayload) ProtoMessage() {}

func (x *HavePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavePayload.ProtoReflect.Descriptor instead.
func (*HavePayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *HavePayload) GetUnitIndex() uint64 {
	if x != nil {
		return x.UnitIndex
	}
	return 0
}

// TransferRequestPayload structure
type TransferRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitIndex     uint64                 `protobuf:"varint,1,opt,name=unit_index,json=unitIndex,proto3" json:"unit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequestPayload) Reset() {
	*x = TransferRequestPayload{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequestPayload) ProtoMessage() {}

func (x *TransferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequestPayload.ProtoReflect.Descriptor instead.
func (*TransferRequestPayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *TransferRequestPayload) GetUnitIndex() uint64 {
	if x != nil {
		return x.UnitIndex
	}
	return 0
}

// TransferPayload structure
type BaoProofNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`    // 32 bytes BLAKE3 hash
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // subtree height (0 = leaf, 1 = parent of 2 leaves, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaoProofNode) Reset() {
	*x = BaoProofNode{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaoProofNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaoProofNode) ProtoMessage() {}

func (x *BaoProofNode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaoProofNode.ProtoReflect.Descriptor instead.
func (*BaoProofNode) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *BaoProofNode) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BaoProofNode) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type BaoProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeafStart     int64                  `protobuf:"varint,1,opt,name=leaf_start,json=leafStart,proto3" json:"leaf_start,omitempty"` // first leaf index of segment
	LeafCount     int64                  `protobuf:"varint,2,opt,name=leaf_count,json=leafCount,proto3" json:"leaf_count,omitempty"` // number of leaves in segment
	Proof         []*BaoProofNode        `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`                           // Bao subtree-compressed proof
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaoProof) Reset() {
	*x = BaoProof{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaoProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaoProof) ProtoMessage() {}

func (x *BaoProof) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaoProof.ProtoReflect.Descriptor instead.
func (*BaoProof) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *BaoProof) GetLeafStart() int64 {
	if x != nil {
		return x.LeafStart
	}
	return 0
}

func (x *BaoProof) GetLeafCount() int64 {
	if x != nil {
		return x.LeafCount
	}
	return 0
}

func (x *BaoProof) GetProof() []*BaoProofNode {
	if x != nil {
		return x.Proof
	}
	return nil
}

type TransferPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitIndex     uint64                 `protobuf:"varint,1,opt,name=unit_index,json=unitIndex,proto3" json:"unit_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Proof         *BaoProof              `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"` // Add this field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPayload) Reset() {
	*x = TransferPayload{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPayload) ProtoMessage() {}

func (x *TransferPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPayload.ProtoReflect.Descriptor instead.
func (*TransferPayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *TransferPayload) GetUnitIndex() uint64 {
	if x != nil {
		return x.UnitIndex
	}
	return 0
}

func (x *TransferPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransferPayload) GetProof() *BaoProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

// RejectPayload structure
type RejectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitIndex     uint64                 `protobuf:"varint,1,opt,name=unit_index,json=unitIndex,proto3" json:"unit_index,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectPayload) Reset() {
	*x = RejectPayload{}
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectPayload) ProtoMessage() {}

func (x *RejectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_peer_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectPayload.ProtoReflect.Descriptor instead.
func (*RejectPayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *RejectPayload) GetUnitIndex() uint64 {
	if x != nil {
		return x.UnitIndex
	}
	return 0
}

func (x *RejectPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pkg_protocol_proto_peer_protocol_proto protoreflect.FileDescriptor

const file_pkg_protocol_proto_peer_protocol_proto_rawDesc = "" +
	"\n" +
	"&pkg/protocol/proto/peer_protocol.proto\x12\bprotocol\"s\n" +
	"\vPeerMessage\x12\x1b\n" +
	"\tinfo_hash\x18\x01 \x01(\fR\binfoHash\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.protocol.PeerMessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"H\n" +
	"\x10HandshakePayload\x12\x1b\n" +
	"\tinfo_hash\x18\x01 \x01(\fR\binfoHash\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\"%\n" +
	"\x0fBitfieldPayload\x12\x12\n" +
	"\x04bits\x18\x01 \x01(\fR\x04bits\",\n" +
	"\vHavePayload\x12\x1d\n" +
	"\n" +
	"unit_index\x18\x01 \x01(\x04R\tunitIndex\"7\n" +
	"\x16TransferRequestPayload\x12\x1d\n" +
	"\n" +
	"unit_index\x18\x01 \x01(\x04R\tunitIndex\"8\n" +
	"\fBaoProofNode\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\"v\n" +
	"\bBaoProof\x12\x1d\n" +
	"\n" +
	"leaf_start\x18\x01 \x01(\x03R\tleafStart\x12\x1d\n" +
	"\n" +
	"leaf_count\x18\x02 \x01(\x03R\tleafCount\x12,\n" +
	"\x05proof\x18\x03 \x03(\v2\x16.protocol.BaoProofNodeR\x05proof\"n\n" +
	"\x0fTransferPayload\x12\x1d\n" +
	"\n" +
	"unit_index\x18\x01 \x01(\x04R\tunitIndex\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12(\n" +
	"\x05proof\x18\x03 \x01(\v2\x12.protocol.BaoProofR\x05proof\"F\n" +
	"\rRejectPayload\x12\x1d\n" +
	"\n" +
	"unit_index\x18\x01 \x01(\x04R\tunitIndex\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*w\n" +
	"\x0fPeerMessageType\x12\x11\n" +
	"\rMSG_HANDSHAKE\x10\x00\x12\x10\n" +
	"\fMSG_BITFIELD\x10\x01\x12\f\n" +
	"\bMSG_HAVE\x10\x02\x12\x0f\n" +
	"\vMSG_REQUEST\x10\x03\x12\x10\n" +
	"\fMSG_TRANSFER\x10\x04\x12\x0e\n" +
	"\n" +
	"MSG_REJECT\x10\x05B/Z-github.com/baoswarm/baobun/pkg/protocol/protob\x06proto3"

var (
	file_pkg_protocol_proto_peer_protocol_proto_rawDescOnce sync.Once
	file_pkg_protocol_proto_peer_protocol_proto_rawDescData []byte
)

func file_pkg_protocol_proto_peer_protocol_proto_rawDescGZIP() []byte {
	file_pkg_protocol_proto_peer_protocol_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_proto_peer_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_peer_protocol_proto_rawDesc), len(file_pkg_protocol_proto_peer_protocol_proto_rawDesc)))
	})
	return file_pkg_protocol_proto_peer_protocol_proto_rawDescData
}

var file_pkg_protocol_proto_peer_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_proto_peer_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_protocol_proto_peer_protocol_proto_goTypes = []any{
	(PeerMessageType)(0),           // 0: protocol.PeerMessageType
	(*PeerMessage)(nil),            // 1: protocol.PeerMessage
	(*HandshakePayload)(nil),       // 2: protocol.HandshakePayload
	(*BitfieldPayload)(nil),        // 3: protocol.BitfieldPayload
	(*HavePayload)(nil),            // 4: protocol.HavePayload
	(*TransferRequestPayload)(nil), // 5: protocol.TransferRequestPayload
	(*BaoProofNode)(nil),           // 6: protocol.BaoProofNode
	(*BaoProof)(nil),               // 7: protocol.BaoProof
	(*TransferPayload)(nil),        // 8: protocol.TransferPayload
	(*RejectPayload)(nil),          // 9: protocol.RejectPayload
}
var file_pkg_protocol_proto_peer_protocol_proto_depIdxs = []int32{
	0, // 0: protocol.PeerMessage.type:type_name -> protocol.PeerMessageType
	6, // 1: protocol.BaoProof.proof:type_name -> protocol.BaoProofNode
	7, // 2: protocol.TransferPayload.proof:type_name -> protocol.BaoProof
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_protocol_proto_peer_protocol_proto_init() }
func file_pkg_protocol_proto_peer_protocol_proto_init() {
	if File_pkg_protocol_proto_peer_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_peer_protocol_proto_rawDesc), len(file_pkg_protocol_proto_peer_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_proto_peer_protocol_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_proto_peer_protocol_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_proto_peer_protocol_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_proto_peer_protocol_proto_msgTypes,
	}.Build()
	File_pkg_protocol_proto_peer_protocol_proto = out.File
	file_pkg_protocol_proto_peer_protocol_proto_goTypes = nil
	file_pkg_protocol_proto_peer_protocol_proto_depIdxs = nil
}
